[project]
name = "ai-python-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shaik Bushra Tabassum", email = "bushratabassum195@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ai-python-lab = "ai_python_lab:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
